export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const SET_CART = "SET_CART";
export const CART_ERROR = "CART_ERROR";
export const CART_LOADING = "CART_LOADING";

export const WISHLIST_LOADING = "WISHLIST_LOADING";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const WISHLIST_ERROR = "WISHLIST_ERROR"
