export const FETCH_KITS_REQUEST = "FETCH_KITS_REQUEST";
export const FETCH_KITS_SUCCESS = "FETCH_KITS_SUCCESS";
export const FETCH_KITS_FAILURE = "FETCH_KITS_FAILURE";

export const CREATE_KIT_REQUEST = "CREATE_KIT_REQUEST";
export const CREATE_KIT_SUCCESS = "CREATE_KIT_SUCCESS";
export const CREATE_KIT_FAILURE = "CREATE_KIT_FAILURE";
