export const CREATE_SHIPPING_INFO_REQUEST = "CREATE_SHIPPING_INFO_REQUEST";
export const CREATE_SHIPPING_INFO_SUCCESS = "CREATE_SHIPPING_INFO_SUCCESS";
export const CREATE_SHIPPING_INFO_FAILURE = "CREATE_SHIPPING_INFO_FAILURE";

export const GET_SHIPPING_INFO_REQUEST = "GET_SHIPPING_INFO_REQUEST";
export const GET_SHIPPING_INFO_SUCCESS = "GET_SHIPPING_INFO_SUCCESS";
export const GET_SHIPPING_INFO_FAILURE = "GET_SHIPPING_INFO_FAILURE";
